// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzwHighSpeedRack.Test.Context;

namespace SzwHighSpeedRack.Test.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseBrand");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseGbProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseGbProduction");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseProductClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Gbname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("Measurement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseProductClass");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseProductGbClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GbName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseProductGbClass");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("AntiEarthquake")
                        .HasColumnType("smallint");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsCancel")
                        .HasColumnType("int");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("StandardStrength")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseProductMaterial");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseQualityStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsRequired")
                        .HasColumnType("smallint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("SampleType")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("StandardId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetCategory")
                        .HasColumnType("int");

                    b.Property<double?>("TargetMax")
                        .HasColumnType("float");

                    b.Property<double?>("TargetMaxInner")
                        .HasColumnType("float");

                    b.Property<double?>("TargetMin")
                        .HasColumnType("float");

                    b.Property<double?>("TargetMinInner")
                        .HasColumnType("float");

                    b.Property<string>("TargetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseQualityStandard");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseSpecifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<double?>("ColdRatio")
                        .HasColumnType("float");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<double?>("ReferLength")
                        .HasColumnType("float");

                    b.Property<double?>("ReferMeterWeight")
                        .HasColumnType("float");

                    b.Property<double?>("ReferPieceCount")
                        .HasColumnType("float");

                    b.Property<double?>("ReferPieceWeight")
                        .HasColumnType("float");

                    b.Property<double?>("ReverseRatio")
                        .HasColumnType("float");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseSpecifications");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.BaseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseTemplate");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstChar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("InJob")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsCanDelete")
                        .HasColumnType("smallint");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MngAdmin");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngDepartmentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChildNum")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depth")
                        .HasColumnType("int");

                    b.Property<short?>("IsBeLock")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsCanDelete")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("ParId")
                        .HasColumnType("int");

                    b.Property<string>("ParPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngDepartmentClass");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngDepartmentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngDepartmentRole");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngDepartmentWorkshopRoleAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsDeny")
                        .HasColumnType("smallint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngDepartmentWorkshopRoleAdmin");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("LoginIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoginTime")
                        .HasColumnType("int");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngLoginLog");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngMenuClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChildNum")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsCanDelete")
                        .HasColumnType("smallint");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsHideInMenu")
                        .HasColumnType("smallint");

                    b.Property<int?>("ParId")
                        .HasColumnType("int");

                    b.Property<string>("ParPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionType")
                        .HasColumnType("int");

                    b.Property<int?>("PlatformType")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MngMenuClass");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsCanDelete")
                        .HasColumnType("smallint");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsLock")
                        .HasColumnType("smallint");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngRole");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngRoleAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngRoleAdmin");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsDeny")
                        .HasColumnType("smallint");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngRolePermission");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apiroot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatCodeRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainCertImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainQrcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainWap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainWebApi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HandoverTime")
                        .HasColumnType("int");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SjbadvertiseId")
                        .HasColumnType("int");

                    b.Property<string>("Sjbsmscode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SjbsmstypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemVersion")
                        .HasColumnType("int");

                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MngSetting");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngSystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngSystemInfo");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.MngSystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SettingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValueLength")
                        .HasColumnType("int");

                    b.Property<int?>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MngSystemSetting");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdBatCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BilletNumber")
                        .HasColumnType("int");

                    b.Property<double?>("BilletPieceWeight")
                        .HasColumnType("float");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<double?>("ProductRate")
                        .HasColumnType("float");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdBatCode");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BundleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsCancelled")
                        .HasColumnType("int");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<int?>("LengthType")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<double?>("MeterWeight")
                        .HasColumnType("float");

                    b.Property<int?>("PieceCount")
                        .HasColumnType("int");

                    b.Property<int?>("ProductDate")
                        .HasColumnType("int");

                    b.Property<string>("RandomCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PdProduct");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQrcodeAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthDate")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQrcodeAuth");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQrcodePrintedLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQrcodePrintedLog");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CheckStatus")
                        .HasColumnType("int");

                    b.Property<int>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("IsPreset")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("QualityInfos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityInfosDynamics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SmeltId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQuality");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQualityHighCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("LastUpdatetime")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQualityHighCode");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQualityProductPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("QualityId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQualityProductPreset");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQualitySmeltCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("LastUpdatetime")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SmeltCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQualitySmeltCode");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdQualitySmeltFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SmeltCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdQualitySmeltFinal");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdStockOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Consignor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverIdCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Lpn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrintTime")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdStockOut");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdStockOutDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockOutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdStockOutDetail");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdWorkshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdWorkshop");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdWorkshopTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Leader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdWorkshopTeam");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.PdWorkshopTeamLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PdWorkshopTeamLog");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SalePrintLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Consignor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("PrintNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("SignetAngle")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalePrintLog");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SalePrintLogDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildType")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PrintId")
                        .HasColumnType("int");

                    b.Property<int?>("PrintNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalePrintLogDetail");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SaleSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Parent")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SaleSeller");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SaleSellerAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthTime")
                        .HasColumnType("int");

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("LengthType")
                        .HasColumnType("int");

                    b.Property<string>("Lpn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("ParentAuthId")
                        .HasColumnType("int");

                    b.Property<int>("ParentSellerId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<int>("StockOutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SaleSellerAuth");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SaleSellerAuthDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthId")
                        .HasColumnType("int");

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SaleSellerAuthDetail");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SaleSellerAuthDetailForSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthId")
                        .HasColumnType("int");

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DataSourceType")
                        .HasColumnType("int");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SaleSellerAuthDetailForSales");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SaleSellerAuthForSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthTime")
                        .HasColumnType("int");

                    b.Property<string>("BatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DataSourceType")
                        .HasColumnType("int");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("LengthType")
                        .HasColumnType("int");

                    b.Property<string>("Lpn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("ParentAuthId")
                        .HasColumnType("int");

                    b.Property<int>("ParentSellerId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.Property<int>("StockOutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SaleSellerAuthForSales");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SiteBasic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarouselImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteTitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatsCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteBasic");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SiteCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depth")
                        .HasColumnType("int");

                    b.Property<int?>("HasModelContent")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ParId")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiteCategory");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SiteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseManageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CheckStatusManageModel")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiteModel");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SiteModelColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FildDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FildIsNull")
                        .HasColumnType("int");

                    b.Property<int?>("FildLength")
                        .HasColumnType("int");

                    b.Property<string>("FildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FildType")
                        .HasColumnType("int");

                    b.Property<string>("FildValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FildWeight")
                        .HasColumnType("int");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("PageShowType")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiteModelColumn");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SiteSinglePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("ReleaseTime")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSinglePage");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.Sitelink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int?>("IsShow")
                        .HasColumnType("int");

                    b.Property<int?>("LinkType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PicHeight")
                        .HasColumnType("int");

                    b.Property<string>("PicLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PicWidth")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sitelink");
                });

            modelBuilder.Entity("SzwHighSpeedRack.Test.Entity.SysMobileCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodeType")
                        .HasColumnType("int");

                    b.Property<int?>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsValaid")
                        .HasColumnType("smallint");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SendTime")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SysMobileCode");
                });
#pragma warning restore 612, 618
        }
    }
}
