// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SzwHighSpeedRackT4.Template
{
    using SzwHighSpeedRackT4;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TemplateController : TemplateControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SzwHighSpeedRack.Entity;
using SzwHighSpeedRack.Service;

namespace SzwHighSpeedRackApi.Controllers
{
    [AllowAnonymous]
    public class ");
            
            #line 14 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Controller : RackBaseApiController\r\n    {\r\n        private IBaseService<");
            
            #line 16 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 16 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service;\r\n\r\n        public ");
            
            #line 18 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Controller(IBaseService<");
            
            #line 18 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 18 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service)\r\n        {\r\n            this.");
            
            #line 20 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 20 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service;\r\n        }\r\n\r\n        [HttpGet(\"{id}\")]\r\n        public MessageModel<");
            
            #line 24 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("> Get(int id)\r\n        {\r\n            ");
            
            #line 26 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(" model = ");
            
            #line 26 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service.FindSingle(f => f.Id == id);\r\n            bool flag = model == null;\r\n   " +
                    "         return new MessageModel<");
            
            #line 28 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(">\r\n            {\r\n                success = !flag,\r\n                msg = !flag ?" +
                    " \"查询成功\" : $\"没有id为{id}的数据\",\r\n                model = !flag ? model : new ");
            
            #line 32 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("()\r\n            };\r\n        }\r\n\r\n        [HttpPost]\r\n        public MessageModel<" +
                    "string> Post([FromBody] ");
            
            #line 37 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            ");
            
            #line 39 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Service.AddEntity(model);
            return new MessageModel<string>
            {
                success = true,
                msg = ""添加成功""
            };
        }

        [HttpDelete(""{id}"")]
        public MessageModel<string> Delete(int id)
        {
            ");
            
            #line 50 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service.DeleteByExp(f => f.Id == id);\r\n            return new MessageModel<string" +
                    ">\r\n            {\r\n                success = true,\r\n                msg = \"删除成功\"\r" +
                    "\n            };\r\n        }\r\n\r\n        [HttpPatch()]\r\n        public MessageModel" +
                    "<PageModel<");
            
            #line 59 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(">> HttpPatch(int pageIndex = 1, int pageSize = 10)\r\n        {\r\n            Messag" +
                    "eModel<PageModel<");
            
            #line 61 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(">> messageModel = new MessageModel<PageModel<");
            
            #line 61 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(">>();\r\n            Expression<Func<");
            
            #line 62 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write(", bool>> exp = null;\r\n            messageModel.model = ");
            
            #line 63 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateModel.EntityName));
            
            #line default
            #line hidden
            this.Write("Service.Page<int>(pageIndex, pageSize, p => p.Id, exp, true);\r\n            messag" +
                    "eModel.success = true;\r\n            messageModel.msg = \"查询成功\";\r\n            retu" +
                    "rn messageModel;\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\szw\source\repos\SzwHighSpeedRack\SzwHighSpeedRackT4\Template\TemplateController.tt"

private global::SzwHighSpeedRackT4.TemplateModel _TemplateModelField;

/// <summary>
/// Access the TemplateModel parameter of the template.
/// </summary>
private global::SzwHighSpeedRackT4.TemplateModel TemplateModel
{
    get
    {
        return this._TemplateModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TemplateModelValueAcquired = false;
if (this.Session.ContainsKey("TemplateModel"))
{
    this._TemplateModelField = ((global::SzwHighSpeedRackT4.TemplateModel)(this.Session["TemplateModel"]));
    TemplateModelValueAcquired = true;
}
if ((TemplateModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TemplateModel");
    if ((data != null))
    {
        this._TemplateModelField = ((global::SzwHighSpeedRackT4.TemplateModel)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TemplateControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
